version: '3.8'
services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app_network
networks:
  app_network:
    driver: bridge