name: CD Pipeline
on:
  push:
    branches:
    - main  # Triggers deployment when code is pushed to main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH and Deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
          cd hng12-stage2-fastapi-book-project  # Change to your project directory
          git pull origin main      # Pull the latest changes
          docker-compose down       # Stop the existing containers
          docker-compose up --build -d  # Rebuild and restart services
        EOF