name: CD Pipeline
on:
  push:
    branches:
    - main  # Triggers deployment when code is pushed to main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH and Deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          cd  hng12-stage2-fastapi-book-project
          git fetch origin main
          git reset --hard origin/main
          
          # Stop and remove old container (if running)
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true

          # Build and run the new container
          sudo docker build -t fastapi-app .
          sudo docker run -d -p 8000:8000 --name fastapi-app fastapi-app

          # Restart Nginx to apply any config changes
          sudo systemctl restart nginx
        EOF